FROM jenkins/jenkins:lts-jdk17

LABEL maintainer='Jk'

USER root
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      docker.io \
      python3 \
      python3-pip \
  && pip install pytest

USER jenkins